import { writeFileSync, mkdirSync, existsSync } from "fs";
import { dirname, join } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");
const outDir = join(root, "public/fonts");

mkdirSync(outDir, { recursive: true });

// Modern Chrome UA — required to receive woff2 URLs from Google Fonts
const userAgent =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36";

const cssUrl =
  "https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@600;700&family=DM+Sans:wght@400;500;600;700&display=swap";

const cssRes = await fetch(cssUrl, { headers: { "User-Agent": userAgent } });
if (!cssRes.ok) {
  console.error("Failed to fetch Google Fonts CSS:", cssRes.status);
  process.exit(1);
}

const css = await cssRes.text();

// Parse with regex that captures the comment BEFORE each @font-face block
// CSS structure: /* subset */\n@font-face { ... }
const blockPattern = /\/\*\s*([^*]+?)\s*\*\/\s*@font-face\s*\{([^}]+)\}/g;

const downloaded = [];
let match;

while ((match = blockPattern.exec(css)) !== null) {
  const subset = match[1].trim();
  const body = match[2];

  // Only keep latin and latin-ext for Turkish content
  if (subset !== "latin" && subset !== "latin-ext") {
    continue;
  }

  const family = body.match(/font-family:\s*'([^']+)'/)?.[1] || "";
  const weight = body.match(/font-weight:\s*(\d+)/)?.[1] || "400";
  const style = body.match(/font-style:\s*(\w+)/)?.[1] || "normal";
  const url = body.match(/src:\s*url\(([^)]+)\)/)?.[1] || "";
  const unicodeRange = body.match(/unicode-range:\s*([^;}]+)/)?.[1]?.trim() || "";

  if (!url || !family) continue;

  const familySlug = family.toLowerCase().replace(/\s+/g, "-");
  const filename = `${familySlug}-${weight}-${subset}.woff2`;

  const fontRes = await fetch(url);
  if (!fontRes.ok) {
    console.warn(`Failed to fetch ${url}: ${fontRes.status}`);
    continue;
  }
  const buffer = Buffer.from(await fontRes.arrayBuffer());
  writeFileSync(join(outDir, filename), buffer);

  downloaded.push({ family, weight, style, subset, filename, unicodeRange, size: buffer.length });
  console.log(`Downloaded: ${filename} (${(buffer.length / 1024).toFixed(1)} KB) — ${subset}`);
}

// Generate @font-face CSS
const cssLines = [
  "/* Self-hosted fonts — auto-generated by scripts/download-fonts.mjs */",
  "/* DO NOT EDIT MANUALLY */",
  "",
];

for (const f of downloaded) {
  cssLines.push(`/* ${f.family} ${f.weight} ${f.subset} */`);
  cssLines.push("@font-face {");
  cssLines.push(`  font-family: '${f.family}';`);
  cssLines.push(`  font-style: ${f.style};`);
  cssLines.push(`  font-weight: ${f.weight};`);
  cssLines.push("  font-display: swap;");
  cssLines.push(`  src: url('/fonts/${f.filename}') format('woff2');`);
  if (f.unicodeRange) cssLines.push(`  unicode-range: ${f.unicodeRange};`);
  cssLines.push("}");
  cssLines.push("");
}

writeFileSync(join(root, "src/styles/fonts.css"), cssLines.join("\n"), "utf-8");

console.log(`\nGenerated ${downloaded.length} @font-face rules in src/styles/fonts.css`);
